package com.nikealarm.nikedrawalarm.other

object Contents {
    const val INTENT_ACTION_SYNC_ALARM = "INTENT_ACTION_SYNC_ALARM"
    const val INTENT_ACTION_PRODUCT_ALARM = "INTENT_ACTION_PRODUCT_ALARM"
    const val INTENT_ACTION_GOTO_WEBSITE = "INTENT_ACTION_GOTO_WEBSITE"
    const val INTENT_ACTION_GOTO_DRAWLIST = "INTENT_ACTION_GOTO_DRAWLIST"
    const val INTENT_ACTION_GOTO_AUTO_ENTER = "INTENT_ACTION_GOTO_AUTO_ENTER"
    const val INTENT_KEY_POSITION = "INTENT_KEY_POSITION"

    const val CHANNEL_ID = "channelId"
    const val DRAW_URL = "drawUrl"

    const val PREFERENCE_NAME_TIME = "PREFERENCE_NAME_TIME"
    const val PREFERENCE_NAME_ALLOW_ALARM = "PREFERENCE_NAME_ALLOW_ALARM"
    const val PREFERENCE_NAME_AUTO_ENTER = "PREFERENCE_NAME_AUTO_ENTER"
    const val PREFERENCE_NAME_AUTO_ENTER_V2 = "PREFERENCE_NAME_AUTO_ENTER_V2"
    const val PREFERENCE_NAME_UPDATE = "PREFERENCE_NAME_UPDATE"

    const val SYNC_ALARM_CODE = 2000
    const val SYNC_ALARM_KEY = "SYNC_ALARM_KEY"

    const val AUTO_ENTER_ALLOW = "AUTO_ENTER_ALLOW"
    const val AUTO_ENTER_ID = "AUTO_ENTER_ID"
    const val AUTO_ENTER_PASSWORD = "AUTO_ENTER_PASSWORD"
    const val AUTO_ENTER_SIZE = "AUTO_ENTER_SIZE"

    const val WORKER_PARSING_DATA = "WORKER_PARSING_DATA"
    const val WORKER_INPUT_DATA_KEY = "WORKER_INPUT_DATA_KEY"
    const val WORKER_PARSING_DATA_OUTPUT_KEY = "WORKER_PARSING_DATA_OUTPUT_KEY"

    const val WORKER_GET_IMAGE = "WORKER_GET_IMAGE"
    const val WORKER_GET_IMAGE_INPUT_KEY = "WORKER_GET_IMAGE_INPUT_KEY"
    const val WORKER_GET_IMAGE_OUTPUT_KEY = "WORKER_GET_IMAGE_OUTPUT_KEY"

    const val WORKER_AUTO_ENTER = "WORKER_AUTO_ENTER"
    const val WORKER_AUTO_ENTER_INPUT_KEY = "WORKER_AUTO_ENTER_INPUT_KEY"
    const val WORKER_AUTO_ENTER_OUTPUT_KEY = "WORKER_AUTO_ENTER_OUTPUT_KEY"
}