package com.nikealarm.nikedrawalarm.other

object Contents {
    const val INTENT_ACTION_SYNC_ALARM = "INTENT_ACTION_SYNC_ALARM"
    const val INTENT_ACTION_PRODUCT_ALARM = "INTENT_ACTION_PRODUCT_ALARM"
    const val INTENT_ACTION_GOTO_WEBSITE = "INTENT_ACTION_GOTO_WEBSITE"
    const val INTENT_ACTION_GOTO_DRAWLIST = "INTENT_ACTION_GOTO_DRAWLIST"
    const val INTENT_KEY_POSITION = "INTENT_KEY_POSITION"

    const val CHANNEL_ID = "channelId"
    const val DRAW_URL = "drawUrl"

    const val PREFERENCE_NAME_TIME = "PREFERENCE_NAME_TIME"
    const val SYNC_ALARM_CODE = 2000

    const val SYNC_ALARM_KEY = "SYNC_ALARM_KEY"

    const val WORKER_INPUT_DATA_KEY = "WORKER_INPUT_DATA_KEY"
    const val WORKER_PARSING_DATA = "WORKER_PARSING_DATA"
}